"""lyric segments per audio

Revision ID: da2864bff90c
Revises: 9eb97803ce6e
Create Date: 2026-09-06 19:17:00.683989
"""
from alembic import op
import sqlalchemy as sa


revision = 'da2864bff90c'
down_revision = '9eb97803ce6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('lyrics_segments', sa.JSON(), nullable=True))
    op.add_column('remixes', sa.Column('lyrics_segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remixes', 'lyrics_segments')
    op.drop_column('generations', 'lyrics_segments')
    # ### end Alembic commands ###
