"""remix quality: which engine model made this version

Revision ID: 13f479e9e0ce
Revises: da2864bff90c
Create Date: 2026-09-07 17:02:09.284083
"""
from alembic import op
import sqlalchemy as sa


revision = '13f479e9e0ce'
down_revision = 'da2864bff90c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remixes', sa.Column('quality', sa.String(length=12), server_default='fast', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remixes', 'quality')
    # ### end Alembic commands ###
