"""ai call telemetry

Revision ID: 3a318be189b0
Revises: 4dcc588dee96
Create Date: 2026-09-06 16:23:52.679406
"""
from alembic import op
import sqlalchemy as sa


revision = '3a318be189b0'
down_revision = '4dcc588dee96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_telemetry_created_at'), 'ai_call_telemetry', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_call_telemetry_feature'), 'ai_call_telemetry', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_call_telemetry_user_id'), 'ai_call_telemetry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_call_telemetry_user_id'), table_name='ai_call_telemetry')
    op.drop_index(op.f('ix_ai_call_telemetry_feature'), table_name='ai_call_telemetry')
    op.drop_index(op.f('ix_ai_call_telemetry_created_at'), table_name='ai_call_telemetry')
    op.drop_table('ai_call_telemetry')
    # ### end Alembic commands ###
