"""uploads stems remixes

Revision ID: 5248de428e08
Revises: 3a318be189b0
Create Date: 2026-09-06 16:50:41.052539
"""
from alembic import op
import sqlalchemy as sa


revision = '5248de428e08'
down_revision = '3a318be189b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('rights_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_generation_id', sa.UUID(), nullable=True),
    sa.Column('vocal_language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'ANALYZING', 'ANALYZED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(length=24), nullable=True),
    sa.Column('lufs', sa.Float(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('lyrics_segments', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_generation_id'], ['generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('remixes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('HYBRID', 'KEEP', 'RESING', 'INSTRUMENTAL', name='remix_mode'), nullable=False),
    sa.Column('preset_key', sa.String(length=40), nullable=True),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('closeness', sa.Float(), nullable=False),
    sa.Column('bpm_to', sa.Float(), nullable=True),
    sa.Column('ai_forward', sa.Integer(), nullable=False),
    sa.Column('harmony', sa.String(length=20), nullable=False),
    sa.Column('chops', sa.Boolean(), nullable=False),
    sa.Column('autotune', sa.Boolean(), nullable=False),
    sa.Column('autotune_strength', sa.Float(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('take_index', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('wav_path', sa.String(length=500), nullable=True),
    sa.Column('mp3_path', sa.String(length=500), nullable=True),
    sa.Column('lufs', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('render_seconds', sa.Float(), nullable=True),
    sa.Column('seed', sa.String(length=40), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remixes_batch_id'), 'remixes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_remixes_upload_id'), 'remixes', ['upload_id'], unique=False)
    op.create_index(op.f('ix_remixes_user_id'), 'remixes', ['user_id'], unique=False)
    op.create_table('stems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('energy_share', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stems_upload_id'), 'stems', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stems_upload_id'), table_name='stems')
    op.drop_table('stems')
    op.drop_index(op.f('ix_remixes_user_id'), table_name='remixes')
    op.drop_index(op.f('ix_remixes_upload_id'), table_name='remixes')
    op.drop_index(op.f('ix_remixes_batch_id'), table_name='remixes')
    op.drop_table('remixes')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
