"""reimagine modes

Revision ID: 9eb97803ce6e
Revises: 5248de428e08
Create Date: 2026-09-06 17:32:01.035891
"""
from alembic import op
import sqlalchemy as sa


revision = '9eb97803ce6e'
down_revision = '5248de428e08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Postgres enums don't gain members from autogenerate — add them explicitly (idempotent).
    op.execute("ALTER TYPE remix_mode ADD VALUE IF NOT EXISTS 'REIMAGINE'")
    op.execute("ALTER TYPE remix_mode ADD VALUE IF NOT EXISTS 'REIMAGINE_KEEP'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remixes', sa.Column('direction', sa.String(length=120), nullable=True))
    op.add_column('remixes', sa.Column('brief', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Postgres cannot drop enum members; the columns are dropped below and the type keeps the extra labels.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remixes', 'brief')
    op.drop_column('remixes', 'direction')
    # ### end Alembic commands ###
