"""init songs generations jobs

Revision ID: 4dcc588dee96
Revises: 
Create Date: 2026-09-06 16:00:46.394483
"""
from alembic import op
import sqlalchemy as sa


revision = '4dcc588dee96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('input_blob', sa.LargeBinary(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_index('ux_jobs_idem_active', 'jobs', ['idempotency_key'], unique=True, postgresql_where="status IN ('QUEUED','RUNNING')")
    op.create_table('songs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('brief', sa.JSON(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=24), nullable=True),
    sa.Column('vocal_language', sa.String(length=8), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RENDERING', 'READY', 'FAILED', name='song_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_user_id'), 'songs', ['user_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('take_index', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('seed', sa.String(length=40), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metas', sa.JSON(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('wav_path', sa.String(length=500), nullable=False),
    sa.Column('mp3_path', sa.String(length=500), nullable=True),
    sa.Column('lufs', sa.Float(), nullable=True),
    sa.Column('render_seconds', sa.Float(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_batch_id'), 'generations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_generations_song_id'), 'generations', ['song_id'], unique=False)
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_song_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_batch_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_songs_user_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index('ux_jobs_idem_active', table_name='jobs', postgresql_where="status IN ('QUEUED','RUNNING')")
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
